'use client';

import { useEffect, useState } from 'react';
import PageShell from '@/components/PageShell';

type User = { id: string; name: string | null; email: string; role: 'STUDENT' | 'REP' | 'SUPER_ADMIN'; status: 'ACTIVE' | 'INACTIVE'; scopes: { level: number }[] };
export default function AdminUsersPage() {
  const [users, setUsers] = useState<User[]>([]); const [message, setMessage] = useState<string | null>(null);
  const load = async () => { const response = await fetch('/api/users'); const data = await response.json(); if (!response.ok) { setMessage(data.error ?? 'Could not load users.'); return; } setUsers(data); };
  useEffect(() => { void load(); }, []);
  const save = async (user: User, role: User['role'], status: User['status']) => { const response = await fetch(`/api/users/${user.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ role, status, ...(role === 'REP' ? { levels: user.scopes.map((scope) => scope.level) } : {}) }) }); const data = await response.json(); if (!response.ok) { setMessage(data.error ?? 'Could not save user.'); return; } void load(); };
  return <PageShell><h1 className="text-2xl font-bold text-[var(--text-primary)]">Manage users</h1><p className="mt-2 text-sm text-[var(--text-muted)]">Grant rep access or deactivate accounts. Rep levels are managed by updating their assigned scopes through the API.</p>{message && <p role="alert" className="mt-4 text-sm text-[var(--text-muted)]">{message}</p>}<div className="mt-6 space-y-3">{users.map((user) => <article key={user.id} className="rounded-xl border border-[var(--border)] bg-[var(--surface)] p-4"><p className="text-sm font-semibold text-[var(--text-primary)]">{user.name ?? user.email}</p><p className="mt-1 text-xs text-[var(--text-muted)]">{user.email}{user.scopes.length ? ` · Levels ${user.scopes.map((scope) => scope.level).join(', ')}` : ''}</p><div className="mt-3 flex flex-wrap gap-2"><select aria-label={`Role for ${user.email}`} defaultValue={user.role} onChange={(event) => void save(user, event.target.value as User['role'], user.status)} className="min-h-11 rounded-lg border border-[var(--border)] bg-[var(--surface-2)] px-3 text-sm text-[var(--text-primary)]"><option value="STUDENT">Student</option><option value="REP">Rep</option><option value="SUPER_ADMIN">Super-admin</option></select><button onClick={() => void save(user, user.role, user.status === 'ACTIVE' ? 'INACTIVE' : 'ACTIVE')} className="min-h-11 px-3 rounded-lg border border-[var(--border)] text-sm text-[var(--text-primary)]">{user.status === 'ACTIVE' ? 'Deactivate' : 'Activate'}</button></div></article>)}</div></PageShell>;
}
