import { Resource } from '@/types/resource';
import { NodeNextRequest } from 'next/dist/server/base-http/node';

export const INITIAL_RESOURCES: Resource[] = [
  {
    id: '1',
    title: 'Introduction to C++ Programming Slides',
    courseCode: 'CSM 157',
    courseTitle: 'Structured Program Design',
    level: 100,
    semester: 1,
    type: 'SLIDES',
    academicYear: '2024/2025',
    fileSize: '4.2 MB',
    status: 'ACTIVE',
    downloadCount: 142,
    uploadedBy: 'Course Rep L100',
    createdAt: '2 hrs ago',
  },
  {
    id: '2',
    title: 'Mid-Sem Past Questions & Solutions',
    courseCode: 'CSM 158',
    courseTitle: 'Discrete Mathematics',
    level: 100,
    semester: 1,
    type: 'PAST_QUESTION',
    academicYear: '2023/2024',
    fileSize: '1.8 MB',
    status: 'ACTIVE',
    downloadCount: 389,
    uploadedBy: 'Super Admin',
    createdAt: '1 day ago',
  },
  {
    id: '3',
    title: 'Data Structures Lab Exercise 3 Manual',
    courseCode: 'CSM 257',
    courseTitle: 'Data Structures',
    level: 200,
    semester: 1,
    type: 'LAB_MANUAL',
    academicYear: '2024/2025',
    fileSize: '850 KB',
    status: 'ACTIVE',
    downloadCount: 95,
    uploadedBy: 'Course Rep L200',
    createdAt: '3 days ago',
  },
  {
    id: '4',
    title: 'Operating Systems Concepts (Silberschatz)',
    courseCode: 'CSM 357',
    courseTitle: 'Operating Systems',
    level: 300,
    semester: 2,
    academicYear: "none",
    type: 'BOOK',
    externalUrl: 'https://drive.google.com/...',
    status: 'ACTIVE',
    downloadCount: 210,
    uploadedBy: 'Super Admin',
    createdAt: '1 week ago',
  },
];